
name: Call Reusable Workflow
on:
  push:
    branches:
      - main

jobs:
  use-reusable:
    uses: IcyGBait/2402FirstRepo/.github/workflows/reusable-test.yaml@main
    with:
      cool_var: "amazing"
